name: glam_ar_sdk
description: Flutter SDK for GlamAR virtual try-on using WebView-based rendering with real-time AR.
version: 1.0.1

homepage: https://www.glamar.io/
repository: https://github.com/pixelbin-io/glamar-flutter

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.1.5
  http: ^1.5.0
  crypto: ^3.0.3
  dio: ^5.9.0
  intl: ^0.20.2
  package_info_plus: ^8.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  http_mock_adapter: ^0.6.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
